AuroraSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Free tier subnet group for Aurora
      SubnetIds:
        - !Ref PrivateSubnet2  # Subnet in AZ 1
        - !Ref PrivateSubnet4  # Subnet in AZ 2
      DBSubnetGroupName: FreeTierSubnetGroup

  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineVersion: 8.0.mysql_aurora.3.06.0
      MasterUsername: admin
      MasterUserPassword: Arfat4545
      DBClusterIdentifier: database-1
      DBSubnetGroupName: !Ref AuroraSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DatabaseSecurityGroup

  AuroraDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref AuroraDBCluster
      Engine: aurora-mysql
      DBInstanceClass: db.r5.large 
      AvailabilityZone: ap-south-1c  # You can specify any AZ here
      DBSubnetGroupName: !Ref AuroraSubnetGroup
      PubliclyAccessible: false

  AuroraDBInstanceReader:
    Type: AWS::RDS::DBInstance
    Properties:
     DBClusterIdentifier: !Ref AuroraDBCluster
     Engine: aurora-mysql
     DBInstanceClass: db.r5.large 
     AvailabilityZone: ap-south-1b  # Place reader instance in a different AZ
     DBSubnetGroupName: !Ref AuroraSubnetGroup
     PubliclyAccessible: false
      

Outputs:
  AuroraDBClusterEndpoint:
    Description: Endpoint of the Aurora DB Cluster
    Value: !GetAtt AuroraDBCluster.Endpoint.Address