Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      SecurityGroupIds:
        - !GetAtt AppTierSecurityGroup.GroupId  # Use the security group ID
      SubnetId: !Ref PrivateSubnet1  # Use the subnet ID
      VpcId: !Ref VPCIac  # Specify the VPC ID
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum install mysql -y
          sudo wget https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
          sudo rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql
          sudo yum install mysql57-community-release-el7-11.noarch.rpm -y
          sudo yum install mysql -y
          RDS_ENDPOINT=!GetAtt AuroraDBCluster.Endpoint.Address
          DB_USERNAME=$(aws ssm get-parameter --name /aurora/db/username --query Parameter.Value --output text)
          DB_PASSWORD=$(aws ssm get-parameter --with-decryption --name /aurora/db/password --query Parameter.Value --output text)
          mysql -h $RDS_ENDPOINT -u $DB_USERNAME -p$DB_PASSWORD -e "CREATE DATABASE webappdb;"
          mysql -h $RDS_ENDPOINT -u $DB_USERNAME -p$DB_PASSWORD -e "SHOW DATABASES;"
          mysql -h $RDS_ENDPOINT -u $DB_USERNAME -p$DB_PASSWORD -e "USE webappdb; CREATE TABLE IF NOT EXISTS transactions(id INT NOT NULL AUTO_INCREMENT, amount DECIMAL(10,2), description VARCHAR(100), PRIMARY KEY(id));"
          mysql -h $RDS_ENDPOINT -u $DB_USERNAME -p$DB_PASSWORD -e "USE webappdb; SHOW TABLES;"
          mysql -h $RDS_ENDPOINT -u $DB_USERNAME -p$DB_PASSWORD -e "USE webappdb; INSERT INTO transactions (amount, description) VALUES ('400', 'groceries');"
      IamInstanceProfile: !Ref DemoEC2Role
      KeyName: ''
      ImageId: ami-001843b876406202a  # Replace with the desired AMI ID
      Tags:
        - Key: Name
          Value: DemoAppEC2Instance
